### ISSUE TITLE
Android V7 App crash for showing the balloon

### ISSUE THREAD

**Issue by SureSh-Doodle-blue** [skydoves/Balloon#382]
- Library Version [v1.4.4 - 1.4.7]
- Affected Device(s) [Emulator Nexus v7 &  Pixel v7]
 
**Describe the Bug:**

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: PID: 3017
    java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3944072 free bytes and 3MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
        at com.skydoves.balloon.overlay.BalloonAnchorOverlayView.prepareBitmap(BalloonAnchorOverlayView.kt:113)
        at com.skydoves.balloon.overlay.BalloonAnchorOverlayView.dispatchDraw(BalloonAnchorOverlayView.kt:96)
        at android.view.View.draw(View.java:17074)
        at android.view.View.updateDisplayListIfDirty(View.java:16053)
        at android.view.View.draw(View.java:16837)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
        at android.view.View.updateDisplayListIfDirty(View.java:16048)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Expected Behavior:**

Should Not crash the app

**Comment by SureSh-Doodle-blue** [comment]
Balloon.Builder(context)
                .setLayout(R.layout.template_tutorial)
                .setWidthRatio(1f)
                .setHeight(BalloonSizeSpec.WRAP)
                .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                .setArrowSize(20)
                .setArrowPosition(0.5f)
                .setCornerRadius(4f)
                .setElevation(16)
                .setBackgroundColorResource(R.color.blue_1482d6)
                .setBalloonAnimation(BalloonAnimation.NONE)
                .setDismissWhenTouchOutside(false)
                .setIsVisibleOverlay(true)
                .setDismissWhenOverlayClicked(false)
                .setLifecycleOwner(lifecycle)
                .build()

**Comment by skydoves** [comment]
I guess you're using a huge size of images (ImageView or something) on your custom layout. Please remove all of Drawable resources in the custom layout and build again. Thanks!

**Comment by SureSh-Doodle-blue** [comment]
@skydoves Thanks for looking this issue.
I didn't use any image views in the custom layout. I am using one rectangle vector drawable for the textview background. It's not huge drawable. Please take a look below

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:radius="@dimen/dp_8" />
    <stroke
        android:width="@dimen/dp_1"
        android:color="@color/white_ffffff" />
</shape>

And the Custom layout having Four TextViews only. There is not having any high memory consumption.

<androidx.constraintlayout.widget.ConstraintLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="@dimen/dp_24">

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvTitle"
        android:layout_width="@dimen/dp_0"
        android:layout_height="wrap_content"
        android:textColor="@color/white_ffffff"
        android:fontFamily="@font/open_sans_semi_bold"
        android:textSize="@dimen/sp_20"
        tools:text="Sort of the ads"
        tools:textColor="@color/black_000000"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvDescription"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textColor="@color/white_ffffff"
        android:fontFamily="@font/open_sans_regular"
        android:textSize="@dimen/sp_16"
        android:layout_marginTop="@dimen/dp_16"
        tools:text="Sort ads by latest or by price"
        tools:textColor="@color/black_000000"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tvTitle"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/btnAction"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@color/white_ffffff"
        android:background="@drawable/bg_btn_tutorial"
        android:fontFamily="@font/open_sans_semi_bold"
        android:paddingStart="@dimen/dp_16"
        android:paddingTop="@dimen/dp_8"
        android:paddingEnd="@dimen/dp_16"
        android:paddingBottom="@dimen/dp_8"
        android:textSize="@dimen/sp_14"
        android:layout_marginTop="@dimen/dp_24"
        tools:text="Next"
        tools:textColor="@color/black_000000"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tvDescription"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvCount"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@color/white_ffffff"
        android:fontFamily="@font/open_sans_regular"
        android:textSize="@dimen/sp_16"
        tools:text="1 of 3"
        tools:textColor="@color/black_000000"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintBottom_toBottomOf="@id/btnAction"
        app:layout_constraintTop_toTopOf="@+id/btnAction"/>
</androidx.constraintlayout.widget.ConstraintLayout>

I guess the issue happen to draw the overlay balloon view,
  at com.skydoves.balloon.overlay.BalloonAnchorOverlayView.prepareBitmap(BalloonAnchorOverlayView.kt:113)
   at com.skydoves.balloon.overlay.BalloonAnchorOverlayView.dispatchDraw(BalloonAnchorOverlayView.kt:96)

**Comment by skydoves** [comment]
This issue seems from creating an overlay bitmap internally. To be honest, there's no clear solution for OOM issues from creating a large bitmap. I would recommend you add the following option on your `AndroidManifest.xml` file: 

```
android:largeHeap="true"
```

**Comment by SureSh-Doodle-blue** [comment]
Okay @skydoves, Thanks for the recommendation. 
But I worried for the lower end device to allocate the memory issue.

**Comment by skydoves** [comment]
Hey @SureSh-Doodle-blue, I think this issue only happens in lower memory devices and large screen devices, such as Nexus v7. It depends on countries, but I think it's a very uncommon use case. I think it would be also great avoiding to show the overlay on lower-level & large screen devices - for this you can utilize AndroidX's WindowManager to check the screen pixel size. Thanks!

**Comment by SureSh-Doodle-blue** [comment]
Thanks for your suggestions, @skydoves. AndroidX's WindowManager having issue on V8.  Better i can use the display metrics. 
I closed this issue based on your suggestions.
