### ISSUE TITLE
App Crash : android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid;

### ISSUE THREAD

**Issue by skauss** [skydoves/Balloon#39]
Hi,
we use the Balloon library to show tooltips.
The balloon is shown with a little delay of 500ms. In Firebase Crashlytics I found some crashes while showing the balloon.

It look's like the user press the back button instantly while the balloon is showing.

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1056)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
       at android.widget.PopupWindow.invokePopup(PopupWindow.java:1478)
       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1316)
       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1272)
       at com.skydoves.balloon.Balloon$showAlignRight$$inlined$show$1.run(Balloon.kt:853)
       at android.os.Handler.handleCallback(Handler.java:873) 
```
This is happens also for 

- com.skydoves.balloon.Balloon$showAlignRight$$inlined$show$1.run(Balloon.kt:853)
- com.skydoves.balloon.Balloon$showAlignTop$$inlined$show$1.run(Balloon.kt:853)
- com.skydoves.balloon.Balloon$showAlignLeft$$inlined$show$1.run(Balloon.kt:853)

It would be great if you catch this exception

- Library Version [e.g. v1.1.1]
- Affected Device(s) : Galaxy Tab A (2018, 10.5) , Galaxy A50 , HTC, U Play , HUAWEI
 
Regards 
Stephan

**Comment by skydoves** [comment]
Hi, @skauss thank you for your issue :)
What attribute did you use for giving a delay to the balloon?
It seems you used `Handler` with `postDelayed`.

**Comment by skauss** [comment]
Hi skydoves,
yes I do 
final Handler handler = new Handler();
handler.postDelayed(() -> balloon.showAlignTop(anchor), 500);

**Comment by skydoves** [comment]
@skauss 
Ah, then you should cancel the hander's runnable when `onPause` is called.

https://stackoverflow.com/questions/4378533/cancelling-a-handler-postdelayed-process
