### ISSUE TITLE
layout_balloon is not inflated right due to drawable missing

### ISSUE THREAD

**Issue by amberkira** [skydoves/Balloon#423]
**Please complete the following information:**
- Library Version [1.2.3]
- Affected Device(s) [Many]
 
**Describe the Bug:**
my app is running with a scale of 700K users, most of them are expirencing good via your lib, thx to you. But a crash is quit upset, 
according to Firebase, it says that:
Fatal Exception: android.view.InflateException: Binary XML file line #46 in com.hellochinese:layout/layout_balloon: Binary XML file line #46 in com.hellochinese:layout/layout_balloon: Error inflating class <unknown>

Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:857)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:964)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1087)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1087)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
       at com.skydoves.balloon.databinding.LayoutBalloonBinding.inflate(LayoutBalloonBinding.java:69)
       at com.skydoves.balloon.Balloon.<init>(Balloon.java:89)
       at com.skydoves.balloon.Balloon$Builder.build(Balloon.java:1426)
       at com.skydoves.balloon.BalloonKt.createBalloon(BalloonKt.java:79)

Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f08007f

I check the source code, line 46 is a drawable called "arrow" in your lib which I guess is the Drawable with resource ID #0x7f08007f

**Expected Behavior:**

How can I fix it?

**Comment by amberkira** [comment]
> Hey, @amberkira, can you change the resource name? Since version 1.3.x Balloon uses different resource names to avoid resource overwriting, but in the previous versions, you should not use the `layout_balloon.xml` naming resource in your project. Because your `layout_balloon.xml` will overwrite the library's layout, and the library will use your layout instead of a pre-defined layout.

thx for your replay, but things is there's no resource in my project named layout_balloon or arrow.png. I finally found this maybe course by Google App Bundle. One of my test mobile[OnePlus 10Pro with android 13 ] can reproduce this problem by installing app from apks which is extracted from aab by Terminal [java -jar bundletool-all-1.7.1.jar build-apks]  and installing by Terminal[java -jar bundletool-all-1.7.1.jar install-apks --apks]

**Comment by skydoves** [comment]
Thanks for the details. But do you have any problems updating to the latest version? (1.5.2). The 1.2.3 version you're using is outdated.

**Comment by amberkira** [comment]
@skydoves I will try it, thx for your remind

**Comment by skydoves** [comment]
@amberkira Please re-open this issue when you face the same issue on the latest version. Thanks!
