### ISSUE TITLE
Balloon.drawableToBitmap

### ISSUE THREAD

**Issue by AbdullahProgrammer426351** [skydoves/Balloon#440]
Fatal Exception: java.lang.OutOfMemoryError:
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1122)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
       at com.skydoves.balloon.Balloon.drawableToBitmap(Balloon.java:2)
       at com.skydoves.balloon.Balloon.o(Balloon.java:33)
       at com.skydoves.balloon.Balloon.adjustArrowColorByMatchingCardBackground(Balloon.java:73)
       at com.skydoves.balloon.Balloon.initializeArrow$lambda$9$lambda$8(Balloon.java:260)
       at com.skydoves.balloon.Balloon$$InternalSyntheticLambda$3$158974064afec9dea4faab63d8ec70dd97d5f21f7d7d5a24c0df0c0f028c074d$0.run(Balloon.java:260)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by skydoves** [comment]
Hi @AbdullahProgrammer426351, would you elaborate on this?

- Which version of Android devices got this issue?
- How frequently?
- Have you ever considered using `android:largeHeap="true"`?

It must be helpful to trace your issue if you would describe the details. Thanks!

**Comment by skydoves** [comment]
Additionally, this issue happens because the `setArrowColorMatchBalloon(true)` method creates a new background of the balloon's body.

**Comment by skydoves** [comment]
I'm closing this issue for now, because there's nothing much that I can do from my side.
