### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by j7arsen** [skydoves/Balloon#443]
**Please complete the following information:**
- Library Version [e.g. v1.5.3]
- Affected Device(s) Emulator Api 23
 
**Describe the Bug:**
java.lang.OutOfMemoryError: Failed to allocate a 10108812 byte allocation with 4194304 free bytes and 5MB until OOM
                                                                                                    	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                                    	at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
                                                                                                    	at com.skydoves.balloon.overlay.BalloonAnchorOverlayView.prepareBitmap(BalloonAnchorOverlayView.kt:113)
                                                                                                    	at com.skydoves.balloon.overlay.BalloonAnchorOverlayView.dispatchDraw(BalloonAnchorOverlayView.kt:96)
                                                                                                    	at android.view.View.draw(View.java:16181)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                                                    	at android.view.View.draw(View.java:15948)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:148)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Add a clear description about the problem.

**Expected Behavior: Not Crash

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hey @j7arsen, could you provide your device information? It seems that the device is really old to malloc large memories (5MB) for your application but it has a large screen.

**Comment by j7arsen** [comment]
PIxel 5 Api 23

**Comment by skydoves** [comment]
Unfortunately, I don't plan to support low-version API with large screens with small heap sizes. Creating an overlay need to create Bitmaps, and it requires a minimum of memories. If your most users are based on low APIs, what about considering adding a large heap option on your AndroidManifest? `android largeheap=true`
