### ISSUE TITLE
Crash: Balloon$showAlignBottom$$inlined$show$1.run error

### ISSUE THREAD

**Issue by KelwayHao** [skydoves/Balloon#671]
- Library Version v1.4.4
- Galaxy S23 Ultra,
- Galaxy S21 5G
- Galaxy S20
 
Hello, @skydoves! Users are getting this error. It is not possible to reproduce step by step. But Crashlytics appear such incidents mainly on samsung and xiaomi. 
 
![image](https://github.com/user-attachments/assets/ebeff561-a994-4d42-b193-b32644972a39)

 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.PopupWindow$PopupDecorView.setFitsSystemWindows(boolean)' on a null object reference
       at android.widget.PopupWindow.invokePopup(PopupWindow.java:1683)
       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1488)
       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1444)
       at com.skydoves.balloon.Balloon$showAlignBottom$$inlined$show$1.run(Balloon.kt:2738)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by skydoves** [comment]
Hey @KelwayHao, it seems that you're trying to access the balloon's internal content before initializing the balloon or after it has already been dismissed.
