### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by epool** [skydoves/Balloon#84]
**Please complete the following information:**
- Library Version [v1.2.0]
- Affected Device(s) Pixel 3 emulator running api 29
 
**Describe the Bug:**

```
    java.lang.ClassCastException: androidx.appcompat.widget.AppCompatTextView cannot be cast to com.skydoves.balloon.vectortext.VectorTextView
        at com.skydoves.balloon.databinding.LayoutBalloonBinding.bind(LayoutBalloonBinding.java:96)
        at com.skydoves.balloon.databinding.LayoutBalloonBinding.inflate(LayoutBalloonBinding.java:67)
        at com.skydoves.balloon.Balloon.<init>(Balloon.kt:86)
        at com.skydoves.balloon.Balloon$Builder.build(Balloon.kt:1314)
```

I'm trying to show this balloon

```
setCornerRadius(4f)
setPadding(14)
setBackgroundColor(ContextCompat.getColor(context, R.color.text_black))
setWidthRatio(1f)
setTextResource(R.string.if_you_want_to_take_more_orders_turn_on_the_auto_acceptance)
setTextColorResource(R.color.white)
setTextSize(14f)
setIconDrawable(context.getDrawableCompat(R.drawable.icon_close))
setIconSize(16)
dismissWhenClicked = true
setLifecycleOwner(this@HomeAcceptationRateView)
setDismissWhenLifecycleOnPause(true)
setOnBalloonClickListener {
    binding.viewModel?.wasSelfAcceptanceTooltipShown = true
}
```

**Expected Behavior:**

Shows the balloon without crash.

**Comment by skydoves** [comment]
Hi, @epool
Could you let me know about your dependency version of `androidx.appcompat:appcompat`?

**Comment by epool** [comment]
@skydoves it's `androidx.appcompat:appcompat:1.1.0`

**Comment by epool** [comment]
I'm sorry, it looks like we were using a custom layout_balloon.xml layout and there we were using AppCompatTextView insted of com.skydoves.balloon.vectortext.VectorTextView.
